### ISSUE TITLE
EHPA metrics for monit crane_autoscaling_effective_hpa_replicas

### ISSUE THREAD

**Issue by saikey0379** [gocrane/crane#318]
**Describe the bug**
when i changed a ehpa type ,for example `auto` to `preview`,the metrics of `craned(crane_autoscaling_effective_hpa_replicas)` add type `preview` ,but type `auto` also exist.

**Reproduce steps**

change scaleStrategy from `Auto` to `Preview`

```yaml
apiVersion: autoscaling.crane.io/v1alpha1
kind: EffectiveHorizontalPodAutoscaler
metadata:
  name: ehpa-simulate
spec:
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 6
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 2
        periodSeconds: 15
      selectPolicy: Max
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ehpa-simulate
  minReplicas: 1
  maxReplicas: 10
  scaleStrategy: Preview
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
```

than `curl -s craned.crane-system.svc.cluster.local:8080/metrics | grep effective_hpa_replicas`

**Expected behavior**

print the current metric type, remove history metrics type or change to zero

**Screenshots**

<img width="564" alt="image" src="https://user-images.githubusercontent.com/41617636/168719731-86028942-536e-4949-b018-11ee75b92ce6.png">

![image](https://user-images.githubusercontent.com/41617636/168719863-88815e57-908a-4dcb-9c48-2e67a9982795.png)

**Environment (please complete the following information):**

 - K8S Version: [e.g. 1.19]
 - Crane Version: [e.g. 0.1.0]
