### ISSUE TITLE
Metric sync exception(resource cpu on pods)

### ISSUE THREAD

**Issue by saikey0379** [gocrane/crane#319]
**Describe the bug**
when I improve CPU load for every pod, the Substitute pods improved
But when the CPU usage decreases, the number of replicas does not reach decrease in time
`resource CPU on pods  (as a percentage of request):  150% (3001m) / 50%`
When I only set hpa, the result is as expected

**Reproduce steps**
1. apply EffectiveHorizontalPodAutoscaler

```yaml
apiVersion: autoscaling.crane.io/v1alpha1
kind: EffectiveHorizontalPodAutoscaler
metadata:
  name: ehpa-simulate
spec:
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 6
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 2
        periodSeconds: 15
      selectPolicy: Max
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ehpa-simulate
  minReplicas: 1
  maxReplicas: 10
  scaleStrategy: Preview
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Pods
    pods:
      metric:
        name: connection_count
      target:
        averageValue: 100
        type: AverageValue
  prediction:
    predictionWindowSeconds: 3600
    predictionAlgorithm:
      algorithmType: dsp
      dsp:
        sampleInterval: "60s"
        historyLength: "3d"
```
2. improve CPU load to 300%, the number of replicas increase
3. CPU usage decreases
4. the number of replicas is not decreased as expected

**Expected behavior**

**Screenshots**

<img width="1399" alt="image" src="https://user-images.githubusercontent.com/41617636/168742128-ebb99ccc-bcec-4e3b-9045-9cbca6068535.png">
<img width="1184" alt="image" src="https://user-images.githubusercontent.com/41617636/168742168-ababe622-8c0f-400e-989a-2b0dbfb6a830.png">

**Environment (please complete the following information):**

 - K8S Version: [e.g. 1.19]
 - Crane Version: [e.g. 0.1.0]
