### ISSUE TITLE
TSP different algorithms can be used for different metrics

### ISSUE THREAD

**Issue by saikey0379** [gocrane/crane#410]
## Describe the feature
when i setup multi metrics with prediction, It provider only one algorithmType and config type.
It is expected that different algorithms can be used for different metrics
```yaml
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: External
    external:
      metric:
        name: test_service
        selector:
          matchLabels:
            type: "test"
            route: "test_service"
      target:
        averageValue: 25000
        type: AverageValue
  prediction:
    predictionWindowSeconds: 600
    predictionAlgorithm:
      algorithmType: dsp
      dsp:
        estimators:
          fft:
            - marginFraction: "0.0"
              minNumOfSpectrumItems: 3
        sampleInterval: "15s"
        historyLength: "16d"
```
