### ISSUE TITLE
historyDuration is too short still exist when set         historyLength: "5d"

### ISSUE THREAD

**Issue by sunnoy** [gocrane/crane#527]
**Describe the bug**
historyDuration is too short still exist when set         historyLength: "5d"
**Reproduce steps**
hpa yaml
```yaml
  prediction:
    predictionWindowSeconds: 3600   # PredictionWindowSeconds is the time window to predict metrics in the future.
    predictionAlgorithm:
      algorithmType: dsp
      dsp:
        sampleInterval: "60s"
        historyLength: "5d"
```
**Expected behavior**
no error 
**Screenshots**
```bash
E0825 16:10:06.701911       1 aggregate_signals.go:37] "Failed to make internal config." err="historyDuration is too short" queryExpr="TimeSeriesPredictionCaller-monitoring/ehpa-php-apache-e82c8d2c-9126-4197-9514-c310a34c8cce/promql__crane_custom.pods_http_requests_qps_sum(rate(http_requests_total[5m])) by (pod)_"
```
**Environment (please complete the following information):**
 - K8S Version: [e.g. 1.23]
 - Crane Version: [e.g. 0.7.0]

source code is 
https://github.com/gocrane/crane/blob/af84e21b472f2ac409465c6dded5aee6e5bac4c3/pkg/prediction/dsp/config.go#L53
 ```go
https://github.com/gocrane/crane/blob/af84e21b472f2ac409465c6dded5aee6e5bac4c3/pkg/prediction/dsp/config.go#L53
	if historyDuration < time.Hour*48 {
		return nil, fmt.Errorf("historyDuration is too short")
	}
```
