### ISSUE TITLE
ehp cant get cpu metrics

### ISSUE THREAD

**Issue by sunnoy** [gocrane/crane#528]
**Describe the bug**

resouce metrics use prometheus-adapter
v1beta1.metrics.k8s.io                 monitoring/prometheus-adapter   True        29h

也可以获取到cpu指标
k top pod -n monitoring httpserver-64db7f5658-7l9gc
NAME                          CPU(cores)   MEMORY(bytes)
httpserver-64db7f5658-7l9gc   0m           10Mi

ehpa
```yaml
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50

- lastTransitionTime: "2022-08-25T08:35:45Z"
    message: 'the HPA was unable to compute the replica count: failed to get cpu utilization:
      missing request for cpu'
    reason: FailedGetResourceMetric
    status: "False"
    type: ScalingActive
```

**Environment (please complete the following information):**
 - K8S Version: [e.g. 1.23]
 - Crane Version: [e.g. 0.7.0]

**Comment by qmhu** [comment]
Hi @sunnoy , you can referring to doc to play with prometheus-adapter:  https://github.com/gocrane/crane/blob/main/docs/tutorials/effective-hpa-with-prometheus-adapter.zh.md

**Comment by sunnoy** [comment]
I just followed this document 。。。

**Comment by qmhu** [comment]
Are you in chat group?

**Comment by sunnoy** [comment]
chat group name is 腾讯云原生技术交流10 ？

**Comment by sunnoy** [comment]
when use "Utilization" ,it need config container resouce limit and reqest

```yaml
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
```
