### ISSUE TITLE
timeseriespredictions cant predictionMetrics

### ISSUE THREAD

**Issue by sunnoy** [gocrane/crane#534]
# ehpa

```yaml
# spec
  prediction:
    predictionWindowSeconds: 600   # PredictionWindowSeconds is the time window to predict metrics in the future.
    predictionAlgorithm:
      algorithmType: dsp
      dsp:
        sampleInterval: "60s"
        historyLength: "3d"

# status
status:
  conditions:
  - lastTransitionTime: "2022-08-26T09:00:08Z"
    message: Effective HPA is ready
    reason: EffectiveHorizontalPodAutoscalerReady
    status: "True"
    type: Ready
  - lastTransitionTime: "2022-08-26T09:00:08Z"
    message: not all metric predicted
    reason: PredictPartial
    status: "False"
    type: PredictionReady
  - lastTransitionTime: "2022-08-26T09:00:08Z"
    message: recommended size matches current size
    reason: ReadyForNewScale
    status: "True"
    type: AbleToScale
  - lastTransitionTime: "2022-08-26T09:00:08Z"
    message: the HPA was able to successfully calculate a replica count from pods
      metric http_requests_qps
    reason: ValidMetricFound
    status: "True"
    type: ScalingActive
  - lastTransitionTime: "2022-08-26T09:00:08Z"
    message: the desired count is within the acceptable range
    reason: DesiredWithinRange
    status: "False"
    type: ScalingLimited
  currentReplicas: 1
  expectReplicas: 1
```

# hpa

```yaml
status:
  conditions:
  - lastTransitionTime: "2022-08-26T07:38:58Z"
    message: recommended size matches current size
    reason: ReadyForNewScale
    status: "True"
    type: AbleToScale
  - lastTransitionTime: "2022-08-26T07:40:28Z"
    message: the HPA was able to successfully calculate a replica count from pods
      metric http_requests_qps
    reason: ValidMetricFound
    status: "True"
    type: ScalingActive
  - lastTransitionTime: "2022-08-26T07:40:28Z"
    message: the desired count is within the acceptable range
    reason: DesiredWithinRange
    status: "False"
    type: ScalingLimited
  currentMetrics:
  - pods:
      current:
        averageValue: 200m
      metric:
        name: http_requests_qps
    type: Pods
  - resource:
      current:
        averageUtilization: 0
        averageValue: "0"
      name: cpu
    type: Resource
  currentReplicas: 1
  desiredReplicas: 1
```

# timeseriespredictions

Does it take three days （historyLength: "3d"）

```yaml
  predictionMetrics:
  - ready: false
    resourceIdentifier: crane_pod_cpu_usage
  - ready: false
    resourceIdentifier: crane_custom.pods_http_requests_qps
```
