### ISSUE TITLE
Optimization: convergence craned permissions

### ISSUE THREAD

**Issue by pmsl** [gocrane/crane#887]
**Describe the bug**

Intruders may use this permission to modify the workload's spec

https://github.com/gocrane/crane/blob/main/deploy/craned/rbac.yaml#L75

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: craned
rules:
......
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - deployments/scale
  - statefulsets
  - statefulsets/scale
  verbs:
  - get
  - list
  - watch
  - update
```

**Reproduce steps**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - K8S Version: [e.g. 1.19]
 - Crane Version: [e.g. 0.1.0]
