### ISSUE TITLE
Put recommendation result into target's annotation

### ISSUE THREAD

**Issue by qmhu** [gocrane/crane#98]
## Describe the feature
currently the recommendation result is present on `recommendation.status`, we can also put it into target's annotation.
this feature should be an option in recommendation's spec.

**Comment by mfanjie** [comment]
can you elaborate more about what's the reason of putting the recommendation to annotation?

**Comment by qmhu** [comment]
Currently we put the recommendation result in `recommendation.status` like this:
```yaml
apiVersion: analysis.crane.io/v1alpha1
kind: Analytics
metadata:
  name: craned-hpa
  namespace: crane-system
spec:
  completionStrategy:
    completionStrategyType: Periodical
    periodSeconds: 86400
  resourceSelectors:
  - apiVersion: apps/v1
    kind: Deployment
    labelSelector: {}
    name: craned
  type: HPA
status:
  lastSuccessfulTime: "2022-01-13T07:26:18Z"
  recommendations:
  - apiVersion: analysis.crane.io/v1alpha1
    kind: Recommendation
    name: craned-hpa-hpa-2f22w
    namespace: crane-system
    uid: 397733ee-986a-4630-af75-736d2b58bfac
```

We can also put the result into target's annotation, then user can view the result from target's annotation, it's convenient for dashboard requirements and so on.
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
  annotations:
    analysis.crane.io/recommend-hpa: {json encoded string}
```
